# Generated by Django 2.0.2 on 2022-11-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labassignment4', '0002_auto_20221022_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='interested',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
